export const Component = {
  RestApplication: Symbol.for("RestApplication"),
  Logger: Symbol.for("Logger"),
  Config: Symbol.for("Config"),
  DatabaseClient: Symbol.for("DatabaseClient"),
  UserService: Symbol.for("UserService"),
  UserModel: Symbol.for("UserModel"),
  OfferService: Symbol.for("OfferService"),
  OfferModel: Symbol.for("OfferModel"),
  CategoryService: Symbol.for("CategoryService"),
  CategoryModel: Symbol.for("CategoryModel"),
  CategoryController: Symbol.for("CategoryController"),
  ExceptionFilter: Symbol.for("ExceptionFilter"),
  UserController: Symbol.for("UserController"),
} as const;
